version: '3.9'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80  
    volumes:
      - ./src:/var/www/html/
      - ./required_files/default.conf:/etc/apache2/sites-enabled/000-default.conf
      
  db:
     image: mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: plzletme!n123
       MYSQL_DATABASE: akash
     volumes:
       - ./mysql-data:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d

  phpmyadmin:
     image: phpmyadmin
     restart: always
     ports:
       - 8080:80
     environment:
       - PMA_ARBITRARY=1
       - UPLOAD_LIMIT=1024M
